import { Inter } from "next/font/google";
import Head from "next/head";
import dynamic from "next/dynamic";

const DynamicComponent = dynamic(() => import("../components/Home"), {
  loading: () => <div>Loading...</div>,
});

const inter = Inter({ subsets: ["latin"] });

export default function Home({ productData, cart }) {
  return (
    <div>
      <Head>
        <title>Ecommerse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center items-center py-1">
        <div className="container mx-auto px-1">
          <img src="/banner.jpg" alt="banner" className="max-w-full h-auto" />
        </div>
      </div>
      <section className="text-gray-600 body-font">
        <div className="container px-5 py-10 mx-auto">
          <div className="flex flex-wrap w-full mb-5 flex-col items-center text-center">
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">
              Choose Your Product
            </h1>
          </div>
        </div>
      </section>

      <DynamicComponent productData={productData} cart={cart} />
    </div>
  );
}
